### PR TITLE
Error system overhaul

### PR DESCRIPTION
**Pull request by funkyfuture**
this is my approach to tackle #93.

though it is still not fully ~~backwards-compatible (submitting custom errors is still missing, but seems rather trivial) and not~~ documented, this thing is at a point where i'd appreciate any review and feedback.

please do not merge yet.

### CODE REVIEW

**Comment by funkyfuture** [comment]
custom validators are now also backward-compatible.

**Comment by funkyfuture** [comment]
a'ight, i added quiet some docs about the mess.

**Comment by nicolaiarocci** [comment]
Stellar. Thanks!

**Comment by funkyfuture** [comment]
oh, i think that could have waited. well, let's see what the world says.

i'll see that i elaborate one or two design questions that trouble me before moving forward with this in #93.

**Comment by funkyfuture** [comment]
and thanks for the corrections.

**Pull request merged**
