### PR TITLE
Refactors `__validate_definitions` to a more generalised manner

### PR DESCRIPTION
**Pull request by funkyfuture**
- skips unnecessary method calls
- adds `normalization_rules`-property to `Validator`

that bugged me since the last refactoring. eventually i did it.

### CODE REVIEW

**Comment by funkyfuture** [comment]
shall i  add an interface for custom validators to redefine mandatory and prioritized rule validation?

**Comment by nicolaiarocci** [comment]
why not :)

**Comment by funkyfuture** [comment]
yeah, thought the same. It even has benefits. ;-)

**Comment by funkyfuture** [comment]
done.

**Comment by nicolaiarocci** [comment]
thanks

**Comment by funkyfuture** [comment]
always a pleasure.

**Pull request merged**
