### PR TITLE
Adds 'propertyschema'-validation

### PR DESCRIPTION
**Pull request by funkyfuture**
this isn't finished at all yet.

but i'm irritated that the failure-test in `test_a_dict_with_propertyschema` passes, as there is currently nothing implemented that detects an error.

@nicolaiarocci any idea what my mistake is here?

### CODE REVIEW

**Comment by funkyfuture** [comment]
done. includes commits from #97 and #97. if these are fine, just merge this one. if they need work, i have to rebase here.

**Comment by nicolaiarocci** [comment]
ack. missed last update. I merged #97 and #99 already.

**Comment by funkyfuture** [comment]
rebased.

**Comment by nicolaiarocci** [comment]
Would you  mind improving the docs with an example or two? People love examples :smiley:

**Comment by funkyfuture** [comment]
yup. done.

**Pull request merged**
