### PR TITLE
Renames keyschema to valueschema

### PR DESCRIPTION
**Pull request by funkyfuture**
- updates schemas for backward-compatibility
- prints a deprecation-warning
- updates documentation
- some code-formatting due to stricter flake8-rules

solves #92

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
I ran the Eve test suite with this on and oh man, did I see a *lot* of deprecation warnings. I will have to also update Eve documentation, else my universe will break once we remove `keyschema` support :smiley:

**Comment by funkyfuture** [comment]
`warning_printed` could be in global namespace to reduce warnings. shall i?

**Comment by nicolaiarocci** [comment]
nope it's ok

**Comment by nicolaiarocci** [comment]
Merged in https://github.com/nicolaiarocci/cerberus/commit/9b5ef21ab50d94cba9de91ee0abc3dbb40333170

**Pull request closed without merging**
