### PR TITLE
Convert self.assert* method calls to plain asserts

### PR DESCRIPTION
**Pull request by nicoddemus**
I used [unittest2pytest](https://pypi.python.org/pypi/unittest2pytest/) to make the conversion.

### CODE REVIEW

**Comment by funkyfuture** [comment]
nice, now get rid of the classes?

Am 5. September 2016 19:16:56 MESZ, schrieb Bruno Oliveira <notifications@github.com>:
>I used [unittest2pytest](https://pypi.python.org/pypi/unittest2pytest/)
>to make the conversion.
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/nicolaiarocci/cerberus/pull/259
>
>-- Commit Summary --
>
>  * Convert self.assert* method calls to plain asserts
>  * Fix flake8 errors
>
>-- File Changes --
>
>    M cerberus/tests/__init__.py (21)
>    M cerberus/tests/tests.py (412)
>
>-- Patch Links --
>
>https://github.com/nicolaiarocci/cerberus/pull/259.patch
>https://github.com/nicolaiarocci/cerberus/pull/259.diff

**Comment by nicoddemus** [comment]
While I agree that the classes can be removed, I'm afraid I won't have time to do this change myself so I think that can be done in a separate PR. :grin:

**Comment by nicolaiarocci** [comment]
Merged after rebase. Thanks!

**Comment by nicoddemus** [comment]
:+1:

**Pull request closed without merging**
